Clinic_Appointment_System/Controllers/AppointmentController.cs
using Clinic_Appointment_System.Models;
using Clinic_Appointment_System.Services;
using Microsoft.AspNetCore.Authorization;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Clinic_Appointment_System.Controllers
{
    [Authorize]
    public class AppointmentController : Controller
    {
        readonly IAppointmentService _appointmentService;
        readonly IDoctorService _doctorService;

        public AppointmentController(IAppointmentService appointmentService, IDoctorService doctorService)
        {
            _appointmentService = appointmentService;
            _doctorService = doctorService;
        }


        public async Task<IActionResult> GetAllAppointments()
        {

            var patientId = HttpContext.Session.GetString("UserId");

            if (string.IsNullOrEmpty(patientId))
            {
                return RedirectToAction("Login", "Account");
            }

            var appointments = await _appointmentService.GetAllAppointmentsAsync(patientId);
            return View(appointments);

        }




        public async Task<IActionResult> GetAppointment(int id)
        {

            return View(await _appointmentService.GetAppointmentByIdAsync(id));
        }


        public async Task<IActionResult> AddAppointment()
        {

            ViewData["DoctorId"] = new SelectList(await _doctorService.GetAllDoctorsAsync(), "DoctorId", "Name");
            return View();

        }
        [HttpPost]
        public async Task<IActionResult> AddAppointment(Appointment appointment)
        {
            var patientId = HttpContext.Session.GetString("UserId");

            if (string.IsNullOrEmpty(patientId))
            {
                return RedirectToAction("Login", "Account");
            }
            appointment.PatientId = patientId;
            if (appointment.AppointmentDate <= DateTime.Now)
            {
                ModelState.AddModelError("AppointmentDate", "The appointment date must be in the future.");
                ViewData["DoctorId"] = new SelectList(await _doctorService.GetAllDoctorsAsync(), "DoctorId", "Name");
                return View(appointment);
            }
            await _appointmentService.AddAppointmentAsync(appointment);
            return RedirectToAction("GetAllAppointments");

        }
        public async Task<IActionResult> EditAppointmentStatus(int id)
        {
            return View(await _appointmentService.GetAppointmentByIdAsync(id));
        }

        [HttpPost]
        public async Task<IActionResult> EditAppointmentStatus(int id, string status)
        {
            await _appointmentService.UpdateAppointmentStatusAsync(id, status);
            return RedirectToAction("GetAllAppointments");
        }


        [HttpGet]
        [HttpDelete]
        public async Task<IActionResult> DeleteAppointment(int id)
        {
            await _appointmentService.DeleteAppointmentAsync(id);


            return RedirectToAction("GetAllAppointments");
        }

    }
}

Clinic_Appointment_System/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> _signInManager
@inject UserManager<User> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Clinic Management System</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/Clinic_Appointment_System.styles.css" asp-append-version="true" />
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
	<header>

		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 sticky-top">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Clinic Appointment System</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
				aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Appointment" asp-action="AddAppointment">Book your Appointment Now!!</a>
						</li>
					</ul>
					<ul class="navbar-nav">
						@if (_signInManager.IsSignedIn(User))
						{
							var firstName = User.FindFirst("FirstName")?.Value;
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="LogOut">Logout   @firstName</a>
							</li>
						}
						else
						{
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
							</li>
						}
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	@* <footer class="border-top position-fixed footer text-muted"> *@
	@* 	<div class="container"> *@
	@* 		&copy; 2025 - Clinic_Appointment_System  *@
	@* 	</div> *@
	@* </footer> *@
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>